# Generated by Django 3.1.5 on 2021-02-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=128)),
                ('topic', models.CharField(default=' ', max_length=128)),
                ('is_user_chat', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='John', max_length=24)),
                ('channels', models.ManyToManyField(related_name='channel_member', to='chat.Channel')),
                ('channels_admin', models.ManyToManyField(related_name='channel_admin', to='chat.Channel')),
                ('star_channels', models.ManyToManyField(blank=True, related_name='star_channels', to='chat.Channel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_chats', models.ManyToManyField(blank=True, related_name='user_chats', to='chat.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='ReadCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_count', models.IntegerField(default=-1)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(default='', max_length=128)),
                ('destination_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channel')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='message_read_count',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.readcount'),
        ),
    ]
