# Generated by Django 3.1.4 on 2020-12-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_channel_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='members',
        ),
        migrations.AddField(
            model_name='profile',
            name='channels',
            field=models.ManyToManyField(to='chat.Channel'),
        ),
    ]
