# Generated by Django 3.1.5 on 2021-02-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210210_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='message_read_count',
        ),
        migrations.AddField(
            model_name='channel',
            name='message_read_count',
            field=models.ManyToManyField(to='chat.ReadCount'),
        ),
    ]
