# Generated by Django 3.1.4 on 2020-12-09 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20201209_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.channel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='channels',
            field=models.ManyToManyField(related_name='channel_member', to='chat.Channel'),
        ),
    ]
