# Generated by Django 3.1.5 on 2021-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210210_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='message_read_count',
            field=models.ManyToManyField(blank=True, to='chat.ReadCount'),
        ),
    ]
