# Generated by Django 3.1.4 on 2020-12-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20201215_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='destination',
            new_name='destination_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
