# Generated by Django 3.1.4 on 2020-12-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20201223_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='channels_admin',
            field=models.ManyToManyField(related_name='channel_admin', to='chat.Channel'),
        ),
    ]
