# Generated by Django 3.1.4 on 2020-12-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_profile_channels_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='topic',
            field=models.CharField(default=' ', max_length=128),
        ),
    ]
