# Generated by Django 3.1.4 on 2020-12-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20201225_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='John', max_length=24),
        ),
    ]
