# Generated by Django 3.1.4 on 2020-12-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='star_channels',
            field=models.ManyToManyField(related_name='star_channels', to='chat.Channel'),
        ),
    ]
