# Generated by Django 3.1.4 on 2021-01-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_profile_star_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='star_channels',
            field=models.ManyToManyField(blank=True, related_name='star_channels', to='chat.Channel'),
        ),
    ]
