# Generated by Django 3.1.4 on 2021-01-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20210116_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_chats',
            field=models.ManyToManyField(blank=True, related_name='user_chats', to='chat.Channel'),
        ),
    ]
