# Generated by Django 3.1.4 on 2021-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_profile_user_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_user_chat',
            field=models.BooleanField(default=False),
        ),
    ]
