# Generated by Django 3.1.5 on 2021-02-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_channel_is_user_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='destination_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.channel'),
        ),
    ]
